### PR TITLE
initial port of php to docker conventions

### PR DESCRIPTION
**Pull request by james-nesbitt**

### CODE REVIEW

**Comment by james-nesbitt** [comment]
see also https://github.com/wunderkraut/docker-container-app-configs/issues/7

**Comment by iler** [comment]
Could you please fix the double definition of user and group in php-fpm.conf-php7. After that this is ok :)

**Comment by james-nesbitt** [comment]
```
 +user = app
+group = app
 listen.owner = app
 listen.group = app
```

This?

EDIT: Never mind, I see it

**Comment by james-nesbitt** [comment]
duplicate user/group definition fixed

(just realized that I removed the one wrong so it look like a larger commit, sorry - it's the same end-result)

**Pull request merged**
